export const freshPickedProducts = [
  {
    productId: 1,
    productImage: "/assets/images/tomatoe.png",
    productName: "Fresh Tomatoes",
    unit: "Per Basket",
    tagText: "Limited Stock",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Ogun",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 3,
  },
  {
    productId: 2,
    productImage: "/assets/images/plantain.png",
    productName: "Fresh Ripe Plantain",
    unit: "Per Bunch",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Unverified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 3,
  },
  {
    productId: 3,
    productImage: "/assets/images/localRice.png",
    productName: "Local White Rice",
    unit: "50kg Bag",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 2,
  },
  {
    productId: 4,
    productImage: "/assets/images/garri.png",
    productName: "Garri Ijebu",
    unit: "10kg Bag",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Unverified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 4,
  },
  {
    productId: 10,
    productImage: "/assets/images/tomatoe.png",
    productName: "Fresh Tomatoes",
    unit: "Per Basket",
    tagText: "Limited Stock",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Ogun",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 1,
  },
  {
    productId: 11,
    productImage: "/assets/images/plantain.png",
    productName: "Fresh Ripe Plantain",
    unit: "Per Bunch",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 4,
  },
  {
    productId: 12,
    productImage: "/assets/images/localRice.png",
    productName: "Local White Rice",
    unit: "50kg Bag",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 3,
  },
  {
    productId: 13,
    productImage: "/assets/images/garri.png",
    productName: "Garri Ijebu",
    unit: "10kg Bag",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 4,
  },
];

export const bestDealsProducts = [
  {
    productId: 5,
    productImage: "/assets/images/plantain.png",
    productName: "Fresh Ripe Plantain",
    unit: "Per Bunch",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 4,
  },
  {
    productId: 6,
    productImage: "/assets/images/tomatoe.png",
    productName: "Fresh Tomatoes",
    unit: "Per Basket",
    tagText: "Limited Stock",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Ogun",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 3,
  },
  {
    productId: 7,
    productImage: "/assets/images/plantain.png",
    productName: "Fresh Ripe Plantain",
    unit: "Per Bunch",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 4,
  },
  {
    productId: 8,
    productImage: "/assets/images/localRice.png",
    productName: "Local White Rice",
    unit: "50kg Bag",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 2,
  },
  {
    productId: 9,
    productImage: "/assets/images/garri.png",
    productName: "Garri Ijebu",
    unit: "10kg Bag",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 4,
  },
  {
    productId: 14,
    productImage: "/assets/images/tomatoe.png",
    productName: "Fresh Tomatoes",
    unit: "Per Basket",
    tagText: "Limited Stock",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Ogun",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 2,
  },
  {
    productId: 15,
    productImage: "/assets/images/plantain.png",
    productName: "Fresh Ripe Plantain",
    unit: "Per Bunch",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 3,
  },
  {
    productId: 16,
    productImage: "/assets/images/localRice.png",
    productName: "Local White Rice",
    unit: "50kg Bag",
    tagText: "Available",
    price: 2500,
    description:
      "Sourced directly from smallholder farmers in Abeokuta, Ogun State, freshly harvested and sorted for top quality.",
    isWatchList: true,
    productDetailImages: [
      "/assets/images/tomatoeDetail1.png",
      "/assets/images/tomatoeDetail2.png",
      "/assets/images/tomatoeDetail1.png",
    ],
    productDetails:
      "Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value. Our Fresh Organic Tomatoes are carefully selected from trusted farms in Abeokuta, Ogun State. Each basket contains approximately 5kg of premium, vine-ripened tomatoes that are perfect for all your cooking needs. These tomatoes are grown using sustainable farming practices without harmful pesticides. They're harvested at peak ripeness to ensure maximum flavor and nutritional value.",
    bestUsedFor:
      "Fresh salads, pasta sauces, stews, soups, jollof rice, and traditional Nigerian dishes.",

    storageTips:
      "Store in a cool, dry place. Refrigerate for longer freshness. Use within 5-7 days of delivery for optimal quality.",
    reviews: [
      {
        reviewId: 1,
        userId: 1,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 2,
        userId: 2,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 3,
        userId: 3,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
      {
        reviewId: 4,
        userId: 4,
        userName: "Oluwa Tobi",
        reviewDate: "5 days ago",
        reviewText: "Good as they said ",
        rate: 2,
      },
      {
        reviewId: 5,
        userId: 5,
        userName: "Tunde Akin",
        reviewDate: "5 days ago",
        reviewText: "Always fresh and well packed. Will definitely order again",
        rate: 4,
      },
    ],
    famersDetails: {
      farmerId: 1,
      farmerName: "Adewale Farms",
      farmerProfilePic: "/assets/images/farmerProfilePic.png",
      verificationStatus: "Verified",
      description:
        "Award-winning organic farm specializing in fresh vegetables and fruits",
      farmerState: "Lagos",
      farmerCountry: "Nigeria",
      yearJoined: 2021,
      totalReviews: 128,
      farmerAverageRating: 4.8,
      totalOrders: 285,
      satisfactionRate: 98,
    },
    productAverageRating: 4,
  },
];
