import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import ContentWrapper from "@/components/ContentWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geologica = localFont({
  src: "./assets/fonts/Geologica/Geologica-Regular.ttf",
  variable: "--font-geologica",
});

const poppins = localFont({
  src: [
    { path: "./assets/fonts/Poppins/Poppins-Regular.ttf", weight: "400" },
    { path: "./assets/fonts/Poppins/Poppins-Medium.ttf", weight: "500" },
    { path: "./assets/fonts/Poppins/Poppins-SemiBold.ttf", weight: "600" },
    { path: "./assets/fonts/Poppins/Poppins-Bold.ttf", weight: "700" },
  ],
  variable: "--font-poppins",
});

const prompt = localFont({
  src: [
    { path: "./assets/fonts/Prompt/Prompt-Regular.ttf", weight: "400" },
    { path: "./assets/fonts/Prompt/Prompt-Medium.ttf", weight: "500" },
    { path: "./assets/fonts/Prompt/Prompt-SemiBold.ttf", weight: "600" },
    { path: "./assets/fonts/Prompt/Prompt-Bold.ttf", weight: "700" },
  ],
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "AgroConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geologica.variable} ${poppins.variable} ${prompt.variable} antialiased`}
      >
        <ContentWrapper>{children}</ContentWrapper>
      </body>
    </html>
  );
}
