import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import ContentWrapper from "@/components/ContentWrapper";
import { AuthProvider } from "@/context/AuthContext";
import { ProfileProvider } from "@/context/ProfileContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geologica = localFont({
  src: [
    { path: "./assets/fonts/Geologica/Geologica-Light.ttf", weight: "300" },
    { path: "./assets/fonts/Geologica/Geologica-Regular.ttf", weight: "400" },
    { path: "./assets/fonts/Geologica/Geologica-Medium.ttf", weight: "500" },
    { path: "./assets/fonts/Geologica/Geologica-SemiBold.ttf", weight: "600" },
    { path: "./assets/fonts/Geologica/Geologica-Bold.ttf", weight: "700" },
  ],
  variable: "--font-geologica",
});

const poppins = localFont({
  src: [
    { path: "./assets/fonts/Poppins/Poppins-Light.ttf", weight: "300" },
    { path: "./assets/fonts/Poppins/Poppins-Regular.ttf", weight: "400" },
    { path: "./assets/fonts/Poppins/Poppins-Medium.ttf", weight: "500" },
    { path: "./assets/fonts/Poppins/Poppins-SemiBold.ttf", weight: "600" },
    { path: "./assets/fonts/Poppins/Poppins-Bold.ttf", weight: "700" },
  ],
  variable: "--font-poppins",
});

const prompt = localFont({
  src: [
    { path: "./assets/fonts/Prompt/Prompt-Light.ttf", weight: "300" },
    { path: "./assets/fonts/Prompt/Prompt-Regular.ttf", weight: "400" },
    { path: "./assets/fonts/Prompt/Prompt-Medium.ttf", weight: "500" },
    { path: "./assets/fonts/Prompt/Prompt-SemiBold.ttf", weight: "600" },
    { path: "./assets/fonts/Prompt/Prompt-Bold.ttf", weight: "700" },
  ],
  variable: "--font-prompt",
});

const raleway = localFont({
  src: [
    { path: "./assets/fonts/Raleway/Raleway-light.ttf", weight: "300" },
    { path: "./assets/fonts/Raleway/Raleway-Regular.ttf", weight: "400" },
    { path: "./assets/fonts/Raleway/Raleway-Medium.ttf", weight: "500" },
    { path: "./assets/fonts/Raleway/Raleway-SemiBold.ttf", weight: "600" },
    { path: "./assets/fonts/Raleway/Raleway-Bold.ttf", weight: "700" },
  ],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "AgroConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${geistSans.variable} ${geologica.variable} ${poppins.variable} ${prompt.variable} antialiased`}
      >
        <AuthProvider>
          <ProfileProvider>
            <ContentWrapper>{children}</ContentWrapper>
          </ProfileProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
