import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Geologica,
  Prompt,
  Poppins,
} from "next/font/google";
import "./globals.css";
import ContentWrapper from "@/components/ContentWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "AgroConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geologica.variable} ${poppins.variable} ${prompt.variable} antialiased`}
      >
        <ContentWrapper>{children}</ContentWrapper>
      </body>
    </html>
  );
}
